export enum PermisosModuloApi{
  Despacho="GESTIONAR DESPACHO",
  CONSULTAR_DESPACHOS="DESP-01",
  REGISTRAR_DESPACHOS="DESP-02",
  ACTUALIZAR_DESPACHOS="DESP-03",
  ELIMINAR_DESPACHOS="DESP-04"


}
